package constants

var INQUIRY_STATUS_NEW_ID uint = 1
var INQUIRY_STATUS_NEW_NAME string = "New"
var INQUIRY_STATUS_APPROVED_ID uint = 2
var INQUIRY_STATUS_APPROVED_NAME string = "Approved"
var INQUIRY_STATUS_APPROVAL_EXPIRED_ID uint = 3
var INQUIRY_STATUS_APPROVAL_EXPIRED_NAME string = "Approval Expired"
var INQUIRY_STATUS_DECLINED_ID uint = 4
var INQUIRY_STATUS_DECLINED_NAME string = "Declined"
var INQUIRY_STATUS_CANCELLED_ID uint = 5
var INQUIRY_STATUS_CANCELLED_NAME string = "Cancelled"

var BOOKING_STATUS_DRAFTED_ID uint = 1
var BOOKING_STATUS_DRAFTED_NAME string = "Drafted"
var BOOKING_STATUS_REQUESTED_ID uint = 2
var BOOKING_STATUS_REQUESTED_NAME string = "Requested" // not used
var BOOKING_STATUS_CONFIRMED_ID uint = 3
var BOOKING_STATUS_CONFIRMED_NAME string = "Confirmed"
var BOOKING_STATUS_IN_PROGRESS_ID uint = 4
var BOOKING_STATUS_IN_PROGRESS_NAME string = "In Progress" // not used
var BOOKING_STATUS_COMPLETED_ID uint = 5
var BOOKING_STATUS_COMPLETED_NAME string = "Completed"
var BOOKING_STATUS_CANCELLED_ID uint = 6
var BOOKING_STATUS_CANCELLED_NAME string = "Cancelled"

var BOOKING_COST_TYPE_TAX_ID uint = 1
var BOOKING_COST_TYPE_TAX_NAME string = "Tax"
var BOOKING_COST_TYPE_CLEANING_FEE_ID uint = 2
var BOOKING_COST_TYPE_CLEANING_FEE_NAME string = "Cleaning Fee"
var BOOKING_COST_TYPE_RENTAL_COST_ID uint = 3
var BOOKING_COST_TYPE_RENTAL_COST_NAME string = "Rental Cost"
var BOOKING_COST_TYPE_BOAT_RENTAL_COST_ID uint = 4
var BOOKING_COST_TYPE_BOAT_RENTAL_COST_NAME string = "Boat Rental Cost"
var BOOKING_COST_TYPE_GAS_REFIL_FEE_ID uint = 5
var BOOKING_COST_TYPE_GAS_REFIL_FEE_NAME string = "Gas Refil Fee"
var BOOKING_COST_TYPE_LABOR_FEE_ID uint = 6
var BOOKING_COST_TYPE_LABOR_FEE_NAME string = "Labor"
var BOOKING_COST_TYPE_DAMAGE_FEE_ID uint = 7
var BOOKING_COST_TYPE_DAMAGE_FEE_NAME string = "Damage Fee"
var BOOKING_COST_TYPE_WEDDING_FEE_ID uint = 8
var BOOKING_COST_TYPE_WEDDING_FEE_NAME string = "Wedding Fee"
var BOOKING_COST_TYPE_EVENT_FEE_ID uint = 9
var BOOKING_COST_TYPE_EVENT_FEE_NAME string = "Event Fee"
var BOOKING_COST_TYPE_OPEN_BAR_ID uint = 10
var BOOKING_COST_TYPE_OPEN_BAR_NAME string = "Open Bar"
var BOOKING_COST_TYPE_CANCELLATION_FEE_ID uint = 11
var BOOKING_COST_TYPE_CANCELLATION_FEE_NAME string = "Cancellation Fee"

var ROOM_TYPE_BEDROOM_ID uint = 1
var ROOM_TYPE_BEDROOM_NAME string = "Bedroom"
var ROOM_TYPE_BATHROOM_ID uint = 2
var ROOM_TYPE_BATHROOM_NAME string = "Bathroom"
var ROOM_TYPE_KITCHEN_ID uint = 3
var ROOM_TYPE_KITCHEN_NAME string = "Kitchen"
var ROOM_TYPE_LIVING_ROOM_ID uint = 4
var ROOM_TYPE_LIVING_ROOM_NAME string = "Living Room"
var ROOM_TYPE_DINING_ROOM_ID uint = 5
var ROOM_TYPE_DINING_ROOM_NAME string = "Dining Room"
var ROOM_TYPE_GARAGE_ID uint = 6
var ROOM_TYPE_GARAGE_NAME string = "Garage"
var ROOM_TYPE_PATIO_ID uint = 7
var ROOM_TYPE_PATIO_NAME string = "Patio"
var ROOM_TYPE_ENTERTAINMENT_ROOM_ID uint = 8
var ROOM_TYPE_ENTERTAINMENT_ROOM_NAME string = "Entertainment Room"

var USER_ROLE_ADMIN_NAME string = "Admin"
var USER_ROLE_ADMIN_ID uint = 1
var USER_ROLE_ACCOUNT_OWNER_NAME string = "Account Owner"
var USER_ROLE_ACCOUNT_OWNER_ID uint = 2
var USER_ROLE_ACCOUNT_MANAGER_NAME string = "Account Manager"
var USER_ROLE_ACCOUNT_MANAGER_ID uint = 3
var USER_ROLE_CLEANING_STAFF_NAME string = "Cleaning Staff"
var USER_ROLE_CLEANING_STAFF_ID uint = 4
var USER_ROLE_MAINTENANCE_STAFF_NAME string = "Maintenance Staff"
var USER_ROLE_MAINTENANCE_STAFF_ID uint = 5

// **************SAAS VALUES**************
var SERVICE_PLAN_BASIC_ID uint = 1
var SERVICE_PLAN_BASIC_NAME string = "Basic"
var SERVICE_PLAN_PRO_HOST_ID uint = 2
var SERVICE_PLAN_PRO_HOST_NAME string = "Pro Host"
var SERVICE_PLAN_FULLY_MANAGED_ID uint = 3
var SERVICE_PLAN_FULLY_MANAGED_NAME string = "Fully Managed"
var SERVICE_PLAN_ENTERPRISE_ID uint = 4
var SERVICE_PLAN_ENTERPRISE_NAME string = "Enterprise"

// *********PAYMENT METHODS*********
var PAYMENT_METHOD_STRIPE_ID uint = 3
